

version: "3.8"

services:
  rates:
    image: fx-rates
    build:
      context: .
      dockerfile: services/rates/Dockerfile
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  gateway:
    image: fx-gateway
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rates:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3