name: Integration Tests CI

on:
  push:
    branches: [main, docker]
  pull_request:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    services:
      docker:
        image: docker:24.0.2-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and run services
        run: docker compose up --build -d

      - name: Wait for services to become healthy
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8080/health; then
              echo "✅ Gateway is healthy"
              break
            fi
            echo "⏳ Waiting for gateway..."
            sleep 3
          done

          # Fail if still unhealthy
          if ! curl -s http://localhost:8080/health; then
            echo "❌ Gateway did not become healthy in time"
            exit 1
          fi

      - name: Test /convert endpoint
        run: |
          echo "🔍 Testing /convert endpoint:"
          curl -v --fail \
            -H "Authorization: Bearer $API_KEY" \
            "http://localhost:8080/convert?from=USD&to=EUR&amount=100"

      - name: Tear down
        if: always()
        run: docker compose down --volumes --remove-orphans
