name: Unit Tests CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.x"

      - name: Verify Go version
        run: go version

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v